<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Tia.Frameworks</RootNamespace>
    <AssemblyName>Tia.Frameworks</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Tia.Core/Tia.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Tia.Core.Tests" />
  </ItemGroup>

</Project>
